/** @type {import('tailwindcss').Config} */
module.exports = {
    content: ["./*.html"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container-low": "#131c2b",
                "outline-variant": "#3b494c",
                "on-error": "#690005",
                "on-tertiary-fixed": "#001945",
                "surface-container-lowest": "#060e1d",
                "on-background": "#dbe2f8",
                "error-container": "#93000a",
                "on-secondary": "#1b247f",
                "surface-tint": "#00daf3",
                "tertiary-container": "#bfd0ff",
                "primary-container": "#00e5ff",
                "on-tertiary-fixed-variant": "#00429c",
                "on-secondary-fixed-variant": "#343d96",
                "inverse-surface": "#dbe2f8",
                "inverse-primary": "#006875",
                "surface-container": "#18202f",
                surface: "#0b1323",
                "on-primary-container": "#00626e",
                "on-primary-fixed": "#001f24",
                error: "#ffb4ab",
                "surface-container-high": "#222a3a",
                "secondary-fixed": "#e0e0ff",
                "on-secondary-container": "#a8afff",
                "tertiary-fixed-dim": "#b0c6ff",
                "secondary-container": "#343d96",
                "primary-fixed-dim": "#00daf3",
                tertiary: "#e8ecff",
                "on-tertiary-container": "#2455af",
                "on-primary-fixed-variant": "#004f58",
                "on-secondary-fixed": "#000767",
                primary: "#c3f5ff",
                background: "#0b1323",
                "on-tertiary": "#002d6f",
                "on-primary": "#00363d",
                "on-error-container": "#ffdad6",
                "inverse-on-surface": "#283041",
                "surface-variant": "#2d3546",
                "surface-container-highest": "#2d3546",
                secondary: "#bdc2ff",
                outline: "#849396",
                "on-surface-variant": "#bac9cc",
                "surface-bright": "#31394a",
                "primary-fixed": "#9cf0ff",
                "tertiary-fixed": "#d9e2ff",
                "surface-dim": "#0b1323",
                "on-surface": "#dbe2f8",
                "secondary-fixed-dim": "#bdc2ff",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
            },
            spacing: {
                xs: "4px",
                margin: "24px",
                lg: "24px",
                xl: "40px",
                gutter: "16px",
                base: "4px",
                sm: "8px",
                md: "16px",
            },
            fontFamily: {
                "headline-lg-mobile": ["Geist"],
                "title-md": ["Geist"],
                "label-sm": ["JetBrains Mono"],
                "headline-lg": ["Geist"],
                "body-sm": ["Geist"],
                "label-md": ["JetBrains Mono"],
                "body-lg": ["Geist"],
                "display-lg": ["Geist"],
            },
            fontSize: {
                "headline-lg-mobile": [
                    "24px",
                    { lineHeight: "32px", fontWeight: "600" },
                ],
                "title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
                "label-sm": [
                    "10px",
                    { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" },
                ],
                "headline-lg": [
                    "32px",
                    { lineHeight: "40px", fontWeight: "600" },
                ],
                "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "label-md": [
                    "12px",
                    { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
                ],
                "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "display-lg": [
                    "48px",
                    { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
                ],
            },
        },
    },
    plugins: [
        require("@tailwindcss/forms"),
        require("@tailwindcss/container-queries"),
    ],
};
